version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - 5434:5432
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: nest

  test-db:
    image: postgres:13
    restart: always
    ports:
      - 5435:5432
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: nest
